name: "Publish module"

on:
  workflow_dispatch:

jobs:
  release:
    uses: "puppetlabs/cat-github-actions/.github/workflows/module_release.yml@a18620f889f9b80be693ceb62fed9067de370c94"
    secrets: "inherit"
