name: "Run Rspec tests"

on:
  push:
  workflow_call:
  pull_request:
      paths:
        - 'lib/**'
        - 'manifests/**'
        - 'spec/**'
        - '.github/workflows/unit-test.yml'
jobs:
  Spec:
    uses: "puppetlabs/cat-github-actions/.github/workflows/module_ci.yml@a18620f889f9b80be693ceb62fed9067de370c94"
    secrets: "inherit"
