name: "Run Rspec tests"

on:
  push:
  workflow_call:
  pull_request:
      paths:
        - 'lib/**'
        - 'manifests/**'
        - 'spec/**'
        - '.github/workflows/unit-test.yml'
jobs:
  unit_tests:
    name: "Run Rspec tests"
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - name: "Run Rspec tests"
        uses: docker://puppet/iac_release:ci
        with:
          args: 'test unit -v'